version: "3"
services:
  nginx:
    build: nginx
    ports: 
      - "80:80"
    volumes:
      - ${NGINX_DIRECTORY}:/var/www/html
      - ${NGINX_LOGS_DIR}:/var/log/nginx/
    networks:
      - internal

  php-fpm:
    build: php-fpm
    networks: 
      - internal
    volumes:
      - ${NGINX_DIRECTORY}:/var/www/html
      - ./php-fpm/php.log:/var/log/fpm-php.www.log

  mysql:
    build: mysql
    ports:
    - "3306:3306"
    volumes:
    - ${DB_DIRECTORY}:/var/lib/mysql
    networks: 
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}

networks:
  internal:
    driver: bridge